environment: localdev

db:
  url: jdbc:postgresql://localhost:15432/motocrud
  username: postgres
  password: 1234
# JPA properties
jpa:
  hibernate:
    ddl-auto: update # When you launch the application for the first time - switch "none" at "create"
  show-sql: true
  database: postgresql
  database-platform: org.hibernate.dialect.PostgreSQLDialect
  open-in-view: false
  generate-ddl: true
  properties:
    hibernate:
      jdbc:
        lob:
          non_contextual_creation: true

spring:
  flyway:
    url: jdbc:postgresql://localhost:15432/motocrud
    user: postgres
    password: 1234
    table: version
    locations: classpath:db/migration
    schemas: migrations

# Logger configuration
logging:
  pattern:
    console: "%d %-5level %logger : %msg%n"
  level:
    org.springframework: info
    org.hibernate: debug
# Server configuration
server:
  port: 8080 #set your port

