environment: localdev

spring:
  # Database
  db:
    url: jdbc:postgresql://localhost:5432/motocrud
    username: postgres
    password: 123
    validationQuery: SELECT 'Hello' from DUAL
    maximumPoolSize: 25
    minimumIdle: 25
    connectionTimeout: 30000
    idleTimeout: 600000
    maxLifetime: 180000
  # JPA properties
  jpa:
    hibernate:
      ddl-auto: create # When you launch the application for the first time - switch "none" at "create"
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true

# Logger configuration
logging:
  pattern:
    console: "%d %-5level %logger : %msg%n"
  level:
    org.springframework: info
    org.hibernate: debug
# Server configuration
server:
  port: 8080 #set your port

